# Generated by Django 4.0.6 on 2022-07-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_contents', models.TextField()),
                ('text_date', models.DateTimeField(auto_now_add=True)),
                ('text_author', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
